/*
 *
 * Stats constants
 *
 */

export const FETCH_AVG_TIME_REQUEST = 'app/Stats/FETCH_AVG_TIME_REQUEST';
export const FETCH_AVG_TIME_SUCCESS = 'app/Stats/FETCH_AVG_TIME_SUCCESS';
export const FETCH_AVG_TIME_FAILURE = 'app/Stats/FETCH_AVG_TIME_FAILURE';
export const FETCH_BORROWING_REQUESTS = 'app/Stats/FETCH_BORROWING_REQUESTS';
export const FETCH_BORROWING_REQUESTS_SUCCESS = 'app/Stats/FETCH_BORROWING_REQUESTS_SUCCESS';
export const FETCH_BORROWING_REQUESTS_FAILURE = 'app/Stats/FETCH_BORROWING_REQUESTS_FAILURE';
export const FETCH_LIBRARIES_REQUEST = 'app/Stats/FETCH_LIBRARIES_REQUEST';
export const FETCH_LIBRARIES_SUCCESS = 'app/Stats/FETCH_LIBRARIES_SUCCESS';
export const FETCH_LIBRARIES_FAILURE = 'app/Stats/FETCH_LIBRARIES_FAILURE';
export const FETCH_COUNTRIES_REQUEST = 'app/Stats/FETCH_COUNTRIES_REQUEST';
export const FETCH_COUNTRIES_SUCCESS = 'app/Stats/FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAILURE = 'app/Stats/FETCH_COUNTRIES_FAILURE';